-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN "deletedAt" TIMESTAMP(3),
ADD COLUMN "deletedBy" TEXT;

-- AlterEnum
ALTER TYPE "AiActivityType" ADD VALUE 'TICKET_KNOWLEDGE_INDEXED';
ALTER TYPE "AiActivityType" ADD VALUE 'TICKET_KNOWLEDGE_RETRIEVED';
