ALTER TYPE "ResolutionReason" ADD VALUE 'CUSTOMER_INACTIVE_HUMAN_HANDLING';
ALTER TYPE "ResolutionReason" ADD VALUE 'CUSTOMER_INACTIVE_SHARED_QUEUE';

ALTER TABLE "AiSettings"
  ADD COLUMN "idleCloseAfterSeconds" INTEGER NOT NULL DEFAULT 28800;
