-- CreateEnum
CREATE TYPE "EscalationReason" AS ENUM ('LOW_KNOWLEDGE_CONFIDENCE', 'NO_RELEVANT_KNOWLEDGE', 'CUSTOMER_REQUESTED_HUMAN', 'AI_FAILED_ATTEMPTS', 'INTERNAL_ACTION_REQUIRED', 'BUSINESS_TOOL_FAILURE', 'CONFLICTING_KNOWLEDGE', 'AI_GENERATION_FAILED', 'AI_TIMEOUT');

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN "escalationReason" "EscalationReason",
ADD COLUMN "escalatedAt" TIMESTAMP(3);
